### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by pepyakin** [comment]
Hey @Atul9 ! Are you still persuing this PR? If so, mind rebasing on top of master?

**Comment by Atul9** [comment]
Hi @pepyakin done. I have rebased from master, please check.

**Comment by axic** [comment]
Would it make sense to check this on CI?

**Comment by pepyakin** [comment]
Yeah, I think it would make a good addition. Wouldn't block merging this PR on it though.

**Comment by pepyakin** [comment]
Thanks @Atul9 !

**Pull request merged**
